jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello there"
orbs:
  jira: circleci/jira@1.3.1
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
      - deploy:
          context:
            - compass-integration-parrishioner
          steps:
            - run: echo "deploying to production"
          post-steps:
            - compass/notify_deployment:
                environment_type: production
