version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "Building..."
      - run: echo "Done building."
  deploy:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "Deploying to production..."
      - run: echo "Done deploying."
orbs:
  jira: circleci/jira@1.3.1
  compass: atlassian-labs/compass@0.1.2
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
  deploy:
    jobs:
      - deploy:
          context:
            - compass-integration-parrishioner
          post-steps:
            - compass/notify_deployment:
                environment_type: production
